# Generated by Django 4.2.2 on 2023-06-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='Img',
            field=models.URLField(default=''),
        ),
    ]
