# Generated by Django 4.2.2 on 2023-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0002_articulo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='Img',
            field=models.TextField(default=''),
        ),
    ]
