# Generated by Django 4.2.2 on 2023-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='CarDetCodArt',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='CarCodCli',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='CarDetCantidad',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='CarDetEstReg',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='CarDetPreUniArt',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='CarDetSubtotal',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='CarDetTot',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
