# Generated by Django 4.2.2 on 2023-07-18 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_pedidocabecera_pedcabcodven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PedCabFec', models.DateField(auto_now_add=True)),
                ('PedDetCantidad', models.IntegerField(default=1)),
                ('PedDetPreUniArt', models.FloatField(default=0.0)),
                ('PedDetSubtotal', models.FloatField(default=0.0)),
                ('PedDetTot', models.FloatField(default=0.0)),
                ('PedDetEstReg', models.BooleanField(default=True)),
                ('PedCabCodCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PedDetArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.articulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='PedDetArtCod',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='PedDetCodCab',
        ),
        migrations.DeleteModel(
            name='PedidoCabecera',
        ),
        migrations.DeleteModel(
            name='PedidoDetalle',
        ),
    ]
