# Generated by Django 4.2.2 on 2023-08-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_articulo_artsto_alter_pedido_peddetcantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='PedDetCantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='PedDetPreUniArt',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='PedDetSubtotal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='PedDetTot',
        ),
        migrations.AddField(
            model_name='carrito',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='PedDetArtCod',
        ),
        migrations.AddField(
            model_name='pedido',
            name='PedDetArtCod',
            field=models.ManyToManyField(to='tienda.carrito'),
        ),
    ]
