# Generated by Django 4.2.2 on 2023-07-17 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_cliente_clidni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarDetCantidad', models.IntegerField(default=1)),
                ('CarDetPreUniArt', models.FloatField(default=0.0)),
                ('CarDetSubtotal', models.FloatField(default=0.0)),
                ('CarDetTot', models.FloatField(default=0.0)),
                ('CarDetEstReg', models.BooleanField(default=True)),
                ('CarCodCli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('CarDetCodArt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.articulo')),
            ],
        ),
    ]
