# Generated by Django 4.2.2 on 2023-07-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_pedidocabecera_pedcabfec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocabecera',
            name='PedCabCodVen',
        ),
    ]
