# Generated by Django 4.2.2 on 2023-07-19 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_pedido_remove_pedidodetalle_peddetartcod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido'),
        ),
    ]
