# Generated by Django 4.2.2 on 2023-07-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_carritoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
