# Generated by Django 4.2.2 on 2023-07-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_delete_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ArtSto',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='PedDetCantidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
