# Generated by Django 4.2.4 on 2023-08-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_articulo_artsto_alter_pedido_peddetcantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='ArtMarCod',
            field=models.ForeignKey(default=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ArtPreUni',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ArtSto',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ArtTipCod',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.tipoarticulo'),
        ),
    ]
